version: '3.8'

services:
  php:
    container_name: news-parser.php
    build:
      context: ./docker/php
    ports:
      - '9111:9000'
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - rabbitmq
  nginx:
    container_name: news-parser.nginx
    image: nginx:stable-alpine
    ports:
      - '8181:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - rabbitmq
  rabbitmq:
    container_name: news-parser.rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - '5672:5672'
      - '15672:15672'
  mysql:
    container_name: news-parser.mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: news_parser
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3316:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
